### ISSUE TITLE
Validating schema using yaml file

### ISSUE THREAD

**Issue by albertogg99** [python-openapi/openapi-schema-validator#124]
Hi, I have developed an openapi.yaml file which contains the schema that my API requests should follow. The schema is not small so I wouldn't like to hardcode it in JSON in my Python schema-validation application. Can I use that yaml file as reference in this schema validator?

**Comment by p1c2u** [comment]
@albertogg99 
Use [json.load](https://docs.python.org/3/library/json.html#json.load) or [yaml.load](https://pyyaml.org/wiki/PyYAMLDocumentation#loading-yaml)

**Comment by albertogg99** [comment]
Thanks!
