### ISSUE TITLE
Cannot import _legacy_validators

### ISSUE THREAD

**Issue by rochacbruno** [python-openapi/openapi-schema-validator#131]
jsonschema released 2 hours ago comes with a change

![2023-09-20_17-20](https://github.com/python-openapi/openapi-schema-validator/assets/458654/c818ec58-5c8a-49d3-9acc-98f188001cc2)

```py
packages/openapi_schema_validator/validators.py:5: in <module>
    from jsonschema import _legacy_validators
E   ImportError: cannot import name '_legacy_validators' from 'jsonschema' (/tmp/gng_testing/lib64/python3.11/site-
```

# suggestion

Do a conditional import on validators.py

```py
try:
    from jsonschema import _legacy_validators
except ImportError:
    from jsonschema import _legacy_keywords as _legacy_validators
```

**Comment by TheTeaCat** [comment]
Facing the same issue right now. Was a result of the following commit: https://github.com/python-jsonschema/jsonschema/commit/931323043b4409a0416f373403bfb52408fc282f

**Comment by rochacbruno** [comment]
@TheTeaCat workaround for now is `jsonschema<=4.19.0`

**Comment by tucked** [comment]
Is there a reason we need to access a private API here?

**Comment by p1c2u** [comment]
Some OpenAPI schema keywords (such as anyOf, oneOf, allOf) are extended versions of Draft ones.

**Comment by Julian** [comment]
> Some OpenAPI schema keywords (such as anyOf, oneOf, allOf) are extended versions of Draft ones.

I've just noticed both the private usage and this issue -- there's no reason to use private APIs even if this is the case. There's perfectly public APIs for doing this, it's e.g. `Draft202012Validator.VALIDATORS["anyOf"]` etc., which get you the JSON Schema Draft 2020-12 implementation of that keyword. That's documented in the [note for `jsonschema.validators.extend`](https://python-jsonschema.readthedocs.io/en/stable/creating/) though let me know if there's an even more obvious place you would have looked, as documentation is always lacking.

And please always raise such things even if there *were* missing APIs -- private indeed means private and can change at any time.
