### ISSUE TITLE
AttributeError: module 'jsonschema._utils' has no attribute 'load_schema'

### ISSUE THREAD

**Issue by nmoreaud** [python-openapi/openapi-schema-validator#70]
jsonschema 4.18.0a1 breaks compatibility, I can't use pytest on my project.

**Comment by yan12125** [comment]
Thank you very much for the fix. Is there a plan for a new stable version with that fix?

**Comment by p1c2u** [comment]
[openapi-schema-validator 0.6.0](https://github.com/python-openapi/openapi-schema-validator/releases/tag/0.6.0) is released now
